/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electionapp;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cianh
 */
public class AdminGUI extends javax.swing.JFrame {
    
    ArrayList<Candidate> adm;

    /**
     * Creates new form AdminGUI
     */
    public AdminGUI() {
        initComponents();
        
        adm = new ArrayList();
        adminTF.setVisible(false);
        adminLB.setVisible(false);
        
        pollBtn.setVisible(false);
        voteBtn.setVisible(false);
        candidateBtn.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameLB = new javax.swing.JLabel();
        passwordLB = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        adminTF = new javax.swing.JTextField();
        adminLB = new javax.swing.JLabel();
        adminRB = new javax.swing.JRadioButton();
        candidateRB = new javax.swing.JRadioButton();
        pollBtn = new javax.swing.JButton();
        candidateBtn = new javax.swing.JButton();
        voteBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel1.setText("Services");

        nameLB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        nameLB.setText("Name:");

        passwordLB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        passwordLB.setText("Password:");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        adminLB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        adminLB.setText("Admin ID:");

        buttonGroup1.add(adminRB);
        adminRB.setText("Administrator");
        adminRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(candidateRB);
        candidateRB.setText("Candidate");
        candidateRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidateRBActionPerformed(evt);
            }
        });

        pollBtn.setText("View Poll");
        pollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollBtnActionPerformed(evt);
            }
        });

        candidateBtn.setText("View Candidate Details");
        candidateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidateBtnActionPerformed(evt);
            }
        });

        voteBtn.setText("View Voter Details ");

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLB)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(adminLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passwordLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminTF)
                    .addComponent(passwordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(nameTF))
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(candidateRB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(228, 228, 228))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(pollBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voteBtn)
                    .addComponent(candidateBtn))
                .addGap(275, 275, 275))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(homeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(387, 387, 387))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(homeBtn)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLB)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminRB)
                            .addComponent(candidateRB))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLB)
                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminLB))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pollBtn)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(candidateBtn)
                        .addGap(40, 40, 40)
                        .addComponent(voteBtn)
                        .addGap(87, 87, 87))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:

        String name; 
        String password; 
        String adminID; 
        
        Candidate a;

        name = nameTF.getText();
        password = passwordTF.getText();
        adminID = adminTF.getText();
        
        if(candidateRB.isSelected()){
            if(name.equals("") || password.equals("") || buttonGroup1.getSelection()==null){
                JOptionPane.showMessageDialog(null, "You must enter your Name and Password");
            }
            else{
                JOptionPane.showMessageDialog(null, "Hi "+name+", Login Successful");
                a = new Candidate(name, password);
                pollBtn.setVisible(true);
                voteBtn.setVisible(false);
                candidateBtn.setVisible(false);
                adm.add(a);
                nameTF.setText("");
                passwordTF.setText("");
            }
        }
        else if(adminRB.isSelected()){
            if(name.equals("") || password.equals("") || adminID.equals("") || buttonGroup1.getSelection()==null){
                JOptionPane.showMessageDialog(null, "You must enter your Name, Password and Admin ID");
            }
            else{
                JOptionPane.showMessageDialog(null, "Hi "+name+", Login Successful");
                adminID = adminTF.getText();
                a = new Admin(name, password, adminID);
                voteBtn.setVisible(true);
                candidateBtn.setVisible(true);
                pollBtn.setVisible(false);
                adm.add(a);
                nameTF.setText("");
                passwordTF.setText("");
                adminTF.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please fill in your details");
            a = new Candidate(name, password);
        }
       
        File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
            try{
            outFile = new File("userLog.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);
            
            for(Candidate x: adm){
                if(x instanceof Candidate){
                    Candidate myCandidate = (Candidate) x;
                    bw.write(myCandidate.printDetails());
                    bw.newLine();
                }
                else if(x instanceof Admin){
                    Admin myAdmin = (Admin) x;
                    bw.write(myAdmin.printDetails());
                    bw.newLine();
                }
                else{
                    bw.write(x.printDetails());
                    bw.newLine();
                }

            }
            bw.close();
            
            
        } catch (IOException e){
            System.out.println("Error writing to file: "+ e);
        }
                    
      
    }//GEN-LAST:event_loginBtnActionPerformed

    private void candidateRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidateRBActionPerformed
        // TODO add your handling code here:
        adminTF.setVisible(false);
        adminLB.setVisible(false);
    }//GEN-LAST:event_candidateRBActionPerformed

    private void adminRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRBActionPerformed
        // TODO add your handling code here:
        adminTF.setVisible(true);
        adminLB.setVisible(true);
    }//GEN-LAST:event_adminRBActionPerformed

    private void candidateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidateBtnActionPerformed
        // TODO add your handling code here:
        String name;
        String occupation;
        String dob;
       
        File inFile;
        FileReader fr;
        BufferedReader br;
        
         try {
            inFile = new File("candidates.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            
            name = br.readLine();
            occupation = br.readLine();
            dob = br.readLine();
            while (name != null) {
                JOptionPane.showMessageDialog(null, "Name: " + name +", Occupation: " + occupation+", Date of Birth: " +dob);
                name = br.readLine();
                occupation = br.readLine();
                dob = br.readLine();
            }
            br.close();
        } catch (IOException e){
            System.out.println(e);             
        } 
         
    }//GEN-LAST:event_candidateBtnActionPerformed

    private void pollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pollBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
           this.setVisible(false);
           MainGUI myGUI2= new MainGUI();
           myGUI2.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLB;
    private javax.swing.JRadioButton adminRB;
    public javax.swing.JTextField adminTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton candidateBtn;
    private javax.swing.JRadioButton candidateRB;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel nameLB;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel passwordLB;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton pollBtn;
    private javax.swing.JButton voteBtn;
    // End of variables declaration//GEN-END:variables
}
