/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electionapp;

/**
 *
 * @author cianh
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminRB = new javax.swing.JRadioButton();
        voterRB = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        mainBackgroundLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Irish Election 2018");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 55));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Please select an option below:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 430, 92));

        buttonGroup1.add(adminRB);
        adminRB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        adminRB.setForeground(new java.awt.Color(0, 0, 0));
        adminRB.setText("Services ");
        adminRB.setContentAreaFilled(false);
        getContentPane().add(adminRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        buttonGroup1.add(voterRB);
        voterRB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        voterRB.setForeground(new java.awt.Color(0, 0, 0));
        voterRB.setText("Vote");
        voterRB.setContentAreaFilled(false);
        voterRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voterRBActionPerformed(evt);
            }
        });
        getContentPane().add(voterRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        nextBtn.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 110, 40));

        mainBackgroundLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/irishflag.jpg"))); // NOI18N
        mainBackgroundLB.setAlignmentY(0.0F);
        mainBackgroundLB.setOpaque(true);
        getContentPane().add(mainBackgroundLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voterRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voterRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voterRBActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        
        if(voterRB.isSelected()){
           this.setVisible(false);
           VoterGUI myGUI2= new VoterGUI();
           myGUI2.setVisible(true);
        }
        else if(adminRB.isSelected()){
            this.setVisible(false);
            AdminGUI myGUI3= new AdminGUI();
            myGUI3.setVisible(true);
        }
        
    }//GEN-LAST:event_nextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel mainBackgroundLB;
    private javax.swing.JButton nextBtn;
    private javax.swing.JRadioButton voterRB;
    // End of variables declaration//GEN-END:variables
}
