/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electionapp;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cianh
 */
public class VoterGUI extends javax.swing.JFrame {
    
    ArrayList<Voter> voterList;

    /**
     * Creates new form VoterGUI
     */
    public VoterGUI() {
        initComponents();
        
        voterList=new ArrayList<Voter>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        vFnameLB = new javax.swing.JLabel();
        vLnameLB = new javax.swing.JLabel();
        vPpsLB = new javax.swing.JLabel();
        occupationLB = new javax.swing.JLabel();
        vFnameTF = new javax.swing.JTextField();
        vLnameTF = new javax.swing.JTextField();
        vPpsTF = new javax.swing.JTextField();
        occupationTF = new javax.swing.JTextField();
        vDobLB = new javax.swing.JLabel();
        vDobTF = new javax.swing.JTextField();
        vSaveBtn = new javax.swing.JButton();
        michaelRB = new javax.swing.JRadioButton();
        gavinRB = new javax.swing.JRadioButton();
        seanRB = new javax.swing.JRadioButton();
        liadhRB = new javax.swing.JRadioButton();
        joanRB = new javax.swing.JRadioButton();
        kevinRB = new javax.swing.JRadioButton();
        gemmaRB = new javax.swing.JRadioButton();
        padraigRB = new javax.swing.JRadioButton();
        peterRB = new javax.swing.JRadioButton();
        johnRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 0, 36)); // NOI18N
        jLabel1.setText("Welcome Voter!");

        vFnameLB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        vFnameLB.setText("First Name:");

        vLnameLB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        vLnameLB.setText("Last Name:");

        vPpsLB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        vPpsLB.setText("PPS Number: ");

        occupationLB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        occupationLB.setText("Occupation:");

        vLnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vLnameTFActionPerformed(evt);
            }
        });

        vDobLB.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        vDobLB.setText("D.O.B (dd/mm/yy):");

        vDobTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vDobTFActionPerformed(evt);
            }
        });

        vSaveBtn.setText("Save");
        vSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vSaveBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(michaelRB);
        michaelRB.setText("Michael D. Higgins");

        buttonGroup1.add(gavinRB);
        gavinRB.setText("Gavin Duffy ");

        buttonGroup1.add(seanRB);
        seanRB.setText("Sean Gallagher");

        buttonGroup1.add(liadhRB);
        liadhRB.setText("Liadh Ni Riada ");
        liadhRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liadhRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(joanRB);
        joanRB.setText("Joan Freeman");

        buttonGroup1.add(kevinRB);
        kevinRB.setText("Kevin Sharkey");

        buttonGroup1.add(gemmaRB);
        gemmaRB.setText("Gemma O'Doherty");

        buttonGroup1.add(padraigRB);
        padraigRB.setText("Padraig O'Ceidgh");

        buttonGroup1.add(peterRB);
        peterRB.setText("Peter Casey");

        buttonGroup1.add(johnRB);
        johnRB.setText("John Groarke");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(occupationLB)
                            .addComponent(vPpsLB)
                            .addComponent(vLnameLB)
                            .addComponent(vFnameLB))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(vFnameTF)
                                .addComponent(vLnameTF)
                                .addComponent(occupationTF, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addComponent(vPpsTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(vSaveBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vDobLB, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vDobTF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(michaelRB)
                    .addComponent(gavinRB)
                    .addComponent(seanRB)
                    .addComponent(liadhRB)
                    .addComponent(joanRB))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peterRB)
                    .addComponent(johnRB)
                    .addComponent(kevinRB)
                    .addComponent(gemmaRB)
                    .addComponent(padraigRB))
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vFnameLB)
                    .addComponent(vFnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(michaelRB)
                    .addComponent(kevinRB))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vLnameLB)
                    .addComponent(vLnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gavinRB)
                    .addComponent(gemmaRB))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vPpsLB)
                    .addComponent(vPpsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seanRB)
                    .addComponent(padraigRB))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupationLB)
                    .addComponent(occupationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liadhRB)
                    .addComponent(peterRB))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vDobLB)
                    .addComponent(vDobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joanRB)
                    .addComponent(johnRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(vSaveBtn)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vDobTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vDobTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vDobTFActionPerformed

    private void vSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vSaveBtnActionPerformed
        // TODO add your handling code here:
        String fname, lname, pps, occupation, dob, vote;
        //int gavinCOUNT, gemmaCount, joanCount, johnCount, kevinCount, liadhCount, michaelCount, padraigCount, peterCount, seanCount;
        vote = "";
        Voter v = null;
        
        fname = vFnameTF.getText();
        lname = vLnameTF.getText();
        pps = vPpsTF.getText();
        occupation = occupationTF.getText();
        dob = vDobTF.getText();
        
        //using an if statement to assign the RB selected to the Voter's details
        if(gavinRB.isSelected()){
            vote = gavinRB.getText();
        }
        else if(gemmaRB.isSelected()){
            vote = gemmaRB.getText();
        }
        else if(joanRB.isSelected()){
            vote = joanRB.getText();
        }
        else if(johnRB.isSelected()){
            vote = johnRB.getText();
        }
        else if(kevinRB.isSelected()){
            vote = kevinRB.getText();
        }
        else if(liadhRB.isSelected()){
            vote = liadhRB.getText();
        }
        else if(michaelRB.isSelected()){
            vote = michaelRB.getText();
        }
        else if (padraigRB.isSelected()){
            vote = padraigRB.getText();
        }
        else if(peterRB.isSelected()){
            vote = peterRB.getText();
        }
        else if(seanRB.isSelected()){
            vote = seanRB.getText();
        }
        voterList.add(v);
        //add each instance of voter (v) to the array list (voterList)
        
        JOptionPane.showMessageDialog(null, "You have added "+fname+" successfully and you're vote is "+vote);
        
        File outFile;
        FileOutputStream fstream;
        ObjectOutputStream ostream;
        
        //ouputing the array list to txt file
        try{
            outFile = new File("output.txt"); 
            fstream = new FileOutputStream(outFile);
            ostream = new ObjectOutputStream(fstream);
            ostream.writeObject(voterList);
        }catch (IOException e){
            System.out.println("Error writing to file: " + e);
        }

    }//GEN-LAST:event_vSaveBtnActionPerformed

    private void liadhRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liadhRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liadhRBActionPerformed

    private void vLnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vLnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vLnameTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton gavinRB;
    private javax.swing.JRadioButton gemmaRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton joanRB;
    private javax.swing.JRadioButton johnRB;
    private javax.swing.JRadioButton kevinRB;
    private javax.swing.JRadioButton liadhRB;
    private javax.swing.JRadioButton michaelRB;
    private javax.swing.JLabel occupationLB;
    private javax.swing.JTextField occupationTF;
    private javax.swing.JRadioButton padraigRB;
    private javax.swing.JRadioButton peterRB;
    private javax.swing.JRadioButton seanRB;
    private javax.swing.JLabel vDobLB;
    private javax.swing.JTextField vDobTF;
    private javax.swing.JLabel vFnameLB;
    private javax.swing.JTextField vFnameTF;
    private javax.swing.JLabel vLnameLB;
    private javax.swing.JTextField vLnameTF;
    private javax.swing.JLabel vPpsLB;
    private javax.swing.JTextField vPpsTF;
    private javax.swing.JButton vSaveBtn;
    // End of variables declaration//GEN-END:variables
}
